version: '3.3'

services:
  server:
    container_name: my-calc-4
    image: my-calc-4:0.0.4
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=my_calc_111
      - PGUSER=my_calc_111
      - PGPASSWORD=my_calc_111
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5477:5477"
    environment:
      - POSTGRES_USER=my_calc_111
      - POSTGRES_PASSWORD=my_calc_111
      - POSTGRES_DB=my_calc_111
    volumes:
      - nps_data:/var/lib/postgresql/data

  client:
    build: client/
    ports:
      - "8087:8087"
    depends_on:
      - server
volumes:
  nps_data: {}


